blog/urls.py
# _*_ coding:utf-8 _*_

from django.conf.urls import url
from . import views

urlpatterns = [
    url(r'^$', views.home, name='home'),  # 访问地址:主机名+端口号/
    url(r'^detail/(?P<pk>\d+)$', views.detail, name='detail'),  # 访问地址:主机名+端口号/detail/pk
    url(r'^category/(?P<pk>\d+)$', views.category, name='category'),  # 访问地址:主机名+端口号/category/pk
    url(r'^blog', views.blog, name='blog'),  # 访问地址:主机名+端口号/blog
    url(r'^ajax_blog', views.ajax_blog, name='ajax_blog'),  # 访问地址:主机名+端口号/blog
    url(r'^date/(\d+)/(\d+)', views.date, name='date'),  # 访问地址:主机名+端口号/date/年/月
    url(r'^findWords', views.findWords, name='findWords'),
    url(r'^looking', views.looking, name='looking'),
    url(r'^record/$', views.record, name='record'),
    url(r'^read_charts/$', views.read_charts, name='read_charts'),
    url(r'^other/$', views.other, name='other'),
]

handler404 = views.page_not_found

blogproject/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from blog.search_indexes import MySeachView
import xadmin


urlpatterns = [
    url(r'^task/', admin.site.urls),
    url(r'^xadmin/', xadmin.site.urls),
    # 通过在根目录下的url加上namespace属性可以实现反向解析的功能
    # 注意:在根目录的url为namespace而项目的url是name
    url(r'^', include('blog.urls', namespace='blog')),    # 该地址就在ip根目录下
    url(r'^', include('comment.urls', namespace='comment')),
    url(r'^', include('likes.urls', namespace='likes')),
    url(r'^', include('user.urls', namespace='user')),
    url(r'^search/', MySeachView(), name='haystack_search'),
    url(r'^ueditor/', include('DjangoUeditor.urls')),
    url(r'^oauth/', include('oauth.urls', namespace='oauth')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

blog/models.py
# _*_ coding:utf-8 _*_

from django.db import models
from django.contrib.auth.models import User  # 引入USER
from django.contrib.contenttypes.fields import GenericRelation
from ckeditor_uploader.fields import RichTextUploadingField
from read_statistics.models import ReadNumExpandMethod, ReadDetail, ReadNum
from DjangoUeditor.models import UEditorField
from django.contrib.contenttypes.models import ContentType
from django.db.models.fields import exceptions


class Category(models.Model):
    """
    Django 要求模型必须继承 models.Model 类。
    Category 只需要一个简单的分类名 name 就可以了。
    CharField 指定了分类名 name 的数据类型，CharField 是字符型，
    CharField 的 max_length 参数指定其最大长度，超过这个长度的分类名就不能被存入数据库。
    """
    CATEGORY_DISPALY = (
        (0, u'展示'),
        (1, u'隐藏'),
    )

    name = models.CharField(max_length=20, verbose_name=u'分类')
    status = models.IntegerField(choices=CATEGORY_DISPALY, default=0, verbose_name='是否发表', null=True)

    class Meta:
        verbose_name = '分类'
        verbose_name_plural = '分类'

    def __str__(self):

        return self.name


class Tag(models.Model):
    """
    标签 Tag 也比较简单，和 Category 一样。
    再次强调一定要继承 models.Model 类！
    """
    name = models.CharField(max_length=100, verbose_name=u'标签')

    class Meta:
        verbose_name = '标签'
        verbose_name_plural = '标签'

    def __str__(self):

        return self.name


class Post(models.Model, ReadNumExpandMethod):
    """
    文章的数据库表稍微复杂一点，主要是涉及的字段更多。
    """
    Post_Display = (
        (0, u'直接发表'),
        (1, u'保留草稿'),
    )
    # 文章标题
    # u'文章标题'可以在后台显示里面的字段名
    title = models.CharField(max_length=70, verbose_name=u'文章标题',)

    # 文章正文，我们使用了 TextField。
    # 存储比较短的字符串可以使用 CharField，但对于文章的正文来说可能会是一大段文本，因此使用 TextField 来存储大段文本。
    body = UEditorField(verbose_name=u'内容', width=580, height=340, toolbars="full",
                        imagePath="images/", filePath="files/",
                        upload_settings={"imageMaxSize": 1204000, "imagePathFormat": "images/%(basename)s_%(datetime)s.%(extname)s"},
                        )

    # 这两个列分别表示文章的创建时间和最后一次修改时间，存储时间的字段用 DateTimeField 类型。
    # auto_now_add=True时间可以被确定为现在的时间,不需要在后台对该字段名进行操作
    created_time = models.DateTimeField(verbose_name=u'创建时间', auto_now_add=True)
    modified_time = models.DateTimeField(verbose_name=u'修改时间', auto_now=True)

    # 文章摘要，可以没有文章摘要，但默认情况下 CharField 要求必须存入数据，否则就会报错。
    # 指定 CharField 的 blank=True 参数值后就可以允许空值了。
    excerpt = models.CharField(verbose_name=u'摘要', max_length=200, blank=True)

    # 这是分类与标签，分类与标签的模型已经定义在上面。
    # 这里把文章对应的数据库表和分类、标签对应的数据库表关联了起来，但是关联形式稍微有点不同。
    # 规定一篇文章只能对应一个分类，但是一个分类下可以有多篇文章，所以使用的是 ForeignKey，即一对多的关联关系。
    # 而对于标签来说，一篇文章可以有多个标签，同一个标签下也可能有多篇文章，所以使用 ManyToManyField，表明这是多对多的关联关系。
    # 文章可以没有标签，因此为标签 tags 指定了 blank=True。

    category = models.ForeignKey(Category, verbose_name=u'分类')
    tags = models.ManyToManyField(Tag, blank=True, verbose_name=u'标签', related_name='tag_post')

    read_detail = GenericRelation(ReadDetail)

    # 文章作者，这里 User 是从 django.contrib.auth.models 导入的。
    # django.contrib.auth 是 Django 内置的应用，专门用于处理网站用户的注册、登录等流程，User 是 Django已经写好的用户模型。
    # 通过 ForeignKey 把文章和 User 关联了起来。
    # 规定一篇文章只能有一个作者，而一个作者可能会写多篇文章，因此这是一对多的关联关系，和 Category 类似。
    # on_delete=models.ON_DOTHING表示删除关联数据,什么也不做
    author = models.ForeignKey(User, on_delete=models.CASCADE, verbose_name=u'作者')

    display = models.IntegerField(choices=Post_Display, verbose_name='是否发表', null=True)

    pimage = models.ImageField(upload_to='upload/images/%Y/%m', max_length=100, verbose_name=u'图片上传', null=True, blank=True)
    # read_num = models.IntegerField(default=0)

    '''
    def get_read_num(self):
        try:
            return self.readnum.read_num

        except exceptions.ObjectDoesNotExist:
            return 0
    '''
    def __str__(self):
        return self.title

    class Meta:
        verbose_name = '文章'
        verbose_name_plural = '文章'
        ordering = ['-created_time']


def get_read_post(self):
    # 此处的一个异常处理,用来捕获没有计数对象的情况
    # 例如在admin后台中,没有计数值会显示为‘-’
    try:
        post = Post.objects.get(id=self.object_id)
        return post.title
    # 对象不存在就返回0
    except exceptions.ObjectDoesNotExist:
        return 0


get_read_post.short_description = '文章'

ReadDetail.get_read_post = get_read_post
ReadNum.get_read_post = get_read_post



'''
class ReadNum(models.Model):
    read_num = models.IntegerField(u'阅读次数', default=0)
    post = models.OneToOneField(Post, on_delete=models.CASCADE)

    def __str__(self):
        return self.read_num

    class Meta:
        verbose_name = '阅读'
        verbose_name_plural = '阅读'
'''

blog/views.py
from django.shortcuts import get_object_or_404, render
from .models import Post, Category  # ReadNum
from django.core.paginator import *   # 导入分页功能
from django.conf import settings   # 导入settings,可以使用其中自定义的全局变量
# contenttypes 是Django内置的一个应用，可以追踪项目中所有app和model的对应关系，并记录在ContentType表中
from user.forms import *  # 导入登录模态框表单
from .tasks import *
from django.http import JsonResponse
from django.views.decorators.csrf import csrf_exempt


def home(request):
    """
    作用:网站首页的视图处理
    :param request: 请求对象
    :return: 首页模板视图
    """
    # 所有分类
    category_list = Category.objects.filter(status=0)

    # 所有博客列表
    # post_list = Post.objects.filter(Q(display=0) | Q(display__isnull=True))
    post_list = cache.get('post_list')
    if post_list is None:
        post_list = Post.objects.filter(Q(display=0) | Q(display__isnull=True)).filter(category__status=0)
        # 60*60表示60秒*60,也就是1小时
        cache.set('post_list', post_list, 30 * 60)

    # 最新发表的15篇博客
    # new_publish = Post.objects.filter(Q(display=0) | Q(display__isnull=True))[:15]
    new_publish = cache.get('new_publish')
    if new_publish is None:
        new_publish = Post.objects.filter(Q(display=0) | Q(display__isnull=True)).filter(category__status=0)[:15]
        # 60*60表示60秒*60,也就是1小时
        cache.set('new_publish', new_publish, 30 * 60)

    # 获取Post模型类或模型的实例，并返回ContentType表示该模型的实例
    post_content_type = ContentType.objects.get_for_model(Post)

    # 最新推荐的15篇博客
    # new_recommend = get_new_recommend_post(post_content_type)
    new_recommend = cache.get('new_recommend')
    if new_recommend is None:
        new_recommend = get_new_recommend_post(post_content_type)
        # 60*60表示60秒*60,也就是1小时
        cache.set('new_recommend', new_recommend, 30 * 60)

    # 随机推荐的15篇博客
    random_recommend = get_random_recomment()

    # 阅读量周榜博客榜单
    # last_7_days_hot_data = get_7_days_read_posts()
    last_7_days_hot_data = cache.get('last_7_days_hot_data')
    if last_7_days_hot_data is None:
        last_7_days_hot_data = get_7_days_read_posts()
        # 60*60表示60秒*60,也就是1小时
        cache.set('last_7_days_hot_data', last_7_days_hot_data, 30 * 60)

    # 阅读量月榜博客榜单
    # last_30_days_hot_data = get_30_days_read_posts()
    last_30_days_hot_data = cache.get('last_30_days_hot_data')
    if last_30_days_hot_data is None:
        last_30_days_hot_data = get_30_days_read_posts()
        # 60*60表示60秒*60,也就是1小时
        cache.set('last_30_days_hot_data', last_30_days_hot_data, 30 * 60)

    # 阅读量总榜博客榜单
    # all_hot_posts = get_all_read_posts()
    all_hot_posts = cache.get('all_hot_posts')
    if all_hot_posts is None:
        all_hot_posts = get_all_read_posts()
        # 60*60表示60秒*60,也就是1小时
        cache.set('all_hot_posts', all_hot_posts, 30 * 60)

    # context用来渲染模板
    context = {
        'category_list': category_list, 'post_count': post_list.count,
        'new_publish': new_publish, 'new_recommend': new_recommend, 'new_publish_display': new_publish[0:5],
        'random_recommend': random_recommend,
        # 'seven_dates': seven_dates,'seven_read_nums': seven_read_nums, 'thirty_dates': thirty_dates,
        # 'thirty_read_nums': thirty_read_nums, 'year': str(year),
        'last_7_days_hot_data': last_7_days_hot_data, 'last_30_days_hot_data': last_30_days_hot_data,
        'all_hot_posts': all_hot_posts, 'LoginModalForm': LoginModalForm(), "RegModalForm": RegModalForm(),
        'ForgotPasswordModalForm': ForgotPasswordModalForm(),
        # 'today_hot_data': today_hot_data,
    }
    return render(request, 'home.html', context)


def read_charts(request):
    """
    获取阅读曲线图
    :param request:
    :return:
    """
    # 获取Post模型类或模型的实例，并返回ContentType表示该模型的实例
    post_content_type = ContentType.objects.get_for_model(Post)
    # 使用自定义的utils工具包get_seven_days_read_data,取出七天内每天的阅读计数总和
    seven_dates, seven_read_nums = get_seven_days_read_data(post_content_type)

    # 使用自定义的utils工具包get_year_read_data,取出当年每月的阅读计数总和
    thirty_dates, thirty_read_nums, year = get_year_read_data(post_content_type)
    # context用来渲染模板
    context = {
        'seven_dates': seven_dates, 'seven_read_nums': seven_read_nums, 'thirty_dates': thirty_dates,
        'thirty_read_nums': thirty_read_nums, 'year': str(year),
    }
    return render(request, 'blog/charts.html', context)


def get_blog_list_common_data(request, post_all_list):
    """
    博客列表,分类列表,时间排序列表的公共分页代码
    :param request: 请求对象
    :param post_all_list: 经过处理后的博客列表
    :return: 公共的context参数
    """
    # 创建一个分页器对象,参数分别是文章列表,每页最大文章数量
    # 这里的EACH_RAGE_BLOG_NUMBER等于10,已经当成常量写进了seetings里
    paginator = Paginator(post_all_list, settings.EACH_RAGE_BLOG_NUMBER)

    # 采用get方式获取用户访问的页码,如果获取不到,默认为第一页
    page_num = request.GET.get('page', 1)

    # 因为用户输入不一定是数字,所以需要用int(page_num),而django里的get_page会自动识别用户输入以及页码范围
    # 注意这里的page_of_list是一个paginator对象

    try:
        page_of_list = paginator.page(int(page_num))
    except Exception:
        page_of_list = paginator.page(1)

    # 获取当前页码
    current_page_num = page_of_list.number

    # page_range = [current_page_num - 2, current_page_num - 1,
    # current_page_num, current_page_num + 1, current_page_num + 2]

    # 获取当前页码前后各两页的页码范围
    # 需要注意判断的是:如果当前页是第一页,那么前两页不能是0,也不能是-1,所以要使用内置max函数来与1比较最大值
    # 同理:如果当前页已经是最后一页,那么就不能取到当前页+2的页码了,所以要使用内置min函数来与最大页码比较最小值
    page_range = list(range(max(current_page_num - 2, 1), current_page_num)) + \
                 list(range(current_page_num, min(current_page_num + 2, paginator.num_pages) + 1))

    # 加上省略页码标记
    # paginator.num_pages表示一共有多少页码
    if page_range[0] - 1 >= 2:
        page_range.insert(0, '...')
    if paginator.num_pages - page_range[-1] >= 2:
        page_range.append('...')

    # 加上首页尾页
    # paginator.num_pages表示一共有多少页码
    if page_range[0] != 1:
        page_range.insert(0, 1)
    if page_range[-1] != paginator.num_pages:
        page_range.append(paginator.num_pages)

    # 所有博客的列表,且按时间越早创建越靠后排
    # post_list = Post.objects.all().order_by('-created_time')

    # count()是延伸下来的方法,用于计算总博客的数量
    # post_count = Post.objects.all().count()

    # 获取所有的分类
    category_list = Category.objects.filter(status=0)

    # 获取博客分类对应的博客数量
    # 给每个category对象绑定post_count字段
    post_category_list = []
    for category in category_list:
        category.post_count = Post.objects.filter(Q(display=0) | Q(display__isnull=True), category=category).count()
        post_category_list.append(category)

    # 获取博客的创建时间,且按创建时间月份排序
    # post_dates = Post.objects.dates('created_time', 'month', order='DESC')
    post_dates = cache.get('post_dates')
    if post_dates is None:
        post_dates = Post.objects.filter(category__status=0).dates('created_time', 'month', order='DESC')
        # 60*60表示60秒*60,也就是1小时
        cache.set('post_dates', post_dates, 30 * 60)

    # 获取日期归档对应的博客数量
    # 利用字典
    post_date_dict = {}
    for post_date in post_dates:
        post_date_count = Post.objects.filter(Q(display=0) | Q(display__isnull=True), category__status=0, created_time__year=post_date.year, created_time__month=post_date.month).count()
        post_date_dict[post_date] = post_date_count

    # 随机推荐的15篇博客
    random_recommend = get_random_recomment()

    # 最新推荐的15篇博客
    post_content_type = ContentType.objects.get_for_model(Post)
    # new_recommend = get_new_recommend_post(post_content_type)
    new_recommend = cache.get('new_recommend')
    if new_recommend is None:
        new_recommend = get_new_recommend_post(post_content_type)
        # 60*60表示60秒*60,也就是1小时
        cache.set('new_recommend', new_recommend, 30*60)

    # 阅读量总榜博客榜单
    # all_hot_posts = get_all_read_posts()
    all_hot_posts = cache.get('all_hot_posts')
    if all_hot_posts is None:
        all_hot_posts = get_all_read_posts()
        # 60*60表示60秒*60,也就是1小时
        cache.set('all_hot_posts', all_hot_posts, 30 * 60)

    # context用来渲染模板
    context = {'post_list': page_of_list.object_list,
               'page_of_list': page_of_list,
               'category_list': category_list,
               'page_range': page_range,
               'post_dates': post_date_dict,
               'random_recommend': random_recommend,
               'new_recommend': new_recommend,
               'all_hot_posts': all_hot_posts,
               'LoginModalForm': LoginModalForm(),
               "RegModalForm": RegModalForm(),
               'ForgotPasswordModalForm': ForgotPasswordModalForm(),
               }
    return context


def blog(request):
    """
    博客列表的视图处理
    :param request: 请求对象
    :return: 博客列表视图
    """
    # post_all_list = Post.objects.all().filter(Q(display=0) | Q(display__isnull=True))
    post_list = cache.get('post_list')
    if post_list is None:
        post_list = Post.objects.filter(Q(display=0) | Q(display__isnull=True)).filter(category__status=0)
        # 60*60表示60秒*60,也就是1小时
        cache.set('post_list', post_list, 30 * 60)

    # 使用公共的get_blog_list_common_data的方法
    context = get_blog_list_common_data(request, post_list)

    # 给request返回一个blog.html文件
    return render(request, 'blog/blog.html', context)


def other(request):
    """
    博客列表的视图处理
    :param request: 请求对象
    :return: 博客列表视图
    """
    # post_all_list = Post.objects.all().filter(Q(display=0) | Q(display__isnull=True))
    post_list = Post.objects.filter(Q(display=0) | Q(display__isnull=True)).filter(category__status=0, category__id=4)

    # 使用公共的get_blog_list_common_data的方法
    context = get_blog_list_common_data(request, post_list)

    # 给request返回一个blog.html文件
    return render(request, 'blog/other.html', context)

@csrf_exempt
def ajax_blog(request):
    """
    ajax加载博客内容
    :param request:
    :return: 博客json数据
    """

    # 采用get方式获取用户访问的页码,如果获取不到,默认为第一页
    page_num = request.POST.get('pagenumber', 1)
    print(page_num)
    post_list = cache.get('post_list')
    if post_list is None:
        post_list = Post.objects.filter(Q(display=0) | Q(display__isnull=True)).filter(category__status=0)
        # 60*60表示60秒*60,也就是1小时
        cache.set('post_list', post_list, 30 * 60)

blog/templates/blog/blog.html
{% extends 'base.html' %}
{% load staticfiles %}
{% load comment_tags %}
{% load likes_tags %}
{% load post_tags %}

{#页面标题#}
{% block title %}
    蒋振飞个人博客 - 全部文章
{% endblock title %}

{% block nav_blog_active %}active{% endblock %}

{% block header_extend %}

{% endblock %}

{% block nav_route %}
    <div class="welcome">您现在的位置是：<a href="{% url 'blog:home' %}">首页</a> > <a href="{% url 'blog:blog' %}">全部文章</a></div>
{% endblock nav_route %}

{% block content %}
    <div class="blogbox">
        <div class="bloglist">
            <ul id="bloglist">
                {% for post in post_list %}
                    <li>
                        <h2><a class="hvr-rotate" href="{% url 'blog:detail' post.id %}" target="_Blank">{{ post.title }}</a></h2>
                        <i><a href="{% url 'blog:detail' post.id %}">

                             {% if post.pimage %}
                                <img class="hvr-grow-shadow" src="/media/{{ post.pimage }}" title="{{post.title}}">
                             {% else %}
                                <img class="hvr-grow-shadow" src="/media/upload/images/2018/12/14e1dfa5574ba3a81a22ad7d11252405.jpg" title="{{post.title}}">
                             {% endif %}

                        </a></i>
                        <p class="blogtext"><a href="{% url 'blog:detail' post.id %}">{{ post.body|cut:'&nbsp;'|striptags|truncatechars:150|safe}}</a></p>
                        <p class="bloginfo">
                            <!--<span>{{ post.author.get_nickname_or_username }}</span>-->
                            <span>{{ post.created_time|date:"Y年m月d日" }}</span>
                            <span><a class="hvr-wobble-vertical" href="{% url 'blog:category' post.category.id %}">{{ post.category }}</a></span>
                            <span>浏览({{ post.get_read_num }}）</span>
                            <span style="padding-left: 0px"><samp class="fa fa-comment"></samp> 评论({% get_comment_count post %})</span>
                        </p>
                        <a href="{% url 'blog:detail' post.id %}" target="_blank" class="viewmore hvr-sweep-to-top hidden">阅读原文</a>
                    </li>
                    {% if not forloop.last %}
                        <div class="blank"></div>
                    {% else %}

                    {% endif %}
                {% empty %}
                    <li class="no-find">暂无博客,敬请期待 !</li>
                {% endfor %}
            </ul>
            <div class="loaddiv hidden">
                <img src="{% static '/img/loading.gif' %}" />
            </div>
        </div>
        <div class="pagelist">
            <a title="Total record">&nbsp;<b>{{ page_of_list.paginator.count }}</b></a>&nbsp;&nbsp;&nbsp;

            {% if page_of_list.has_previous %}
                <a href="?page={{ page_of_list.previous_page_number }}">
                    上一页
                </a>
            {% endif %}

            {% for page_num in page_range %}
                {# 判断是否当前页 #}
                {% if page_num == page_of_list.number %}
                    {# 如果是当前页就设置高亮 #}
                    <b>{{ page_num }}</b>&nbsp;
                {% else %}
                    {% if page_num == '...' %}
                        <span class="hidden-xs">{{ page_num }}</span>
                    {% else %}
                        <a class="hidden-xs" href="?page={{ page_num }}">{{ page_num }}</a>
                    {% endif %}
                {% endif %}
            {% endfor %}


            {% if page_of_list.has_next %}
                <a href="?page={{ page_of_list.next_page_number }}">
                    下一页
                </a>
            {% endif %}

            <span class="hidden-xs" id="page_goto"><input type="text" value="6"></span>
            <a class="hidden-xs" href="javascript:void(0);" onclick="page_jump();">Go</a>

        </div>
    </div>
    {% block side_list %}
        <div class="rside">
        <div class="news" id="hot">
            <h2 class="newstitle"><span><a href="{% url 'blog:blog' %}"><u>更多</u></a></span><b>热门排行</b></h2>
            <ul>
                {% for post in all_hot_posts %}
                    <li><a class="hvr-curl-bottom-right" href="{% url 'blog:detail' post.id %}" target="_Blank"><span>{{ post.created_time|date:"Y-m-d" }}</span>{{ post.title|striptags|truncatechars:23|safe }}</a></li>
                {% empty %}
                    <span>暂无排行 !</span>
                {% endfor %}
            </ul>
        </div>
        <div class="news" id="random">
            <h2 class="newstitle"><span><a href="{% url 'blog:blog' %}"><u>更多</u></a></span><b>随机推荐</b></h2>
            <ul>
                 {% for post in random_recommend %}
                    <li><a class="hvr-curl-bottom-right" href="{% url 'blog:detail' post.id %}" target="_Blank"><span>{{ post.created_time|date:"Y-m-d" }}</span>{{ post.title|striptags|truncatechars:23|safe }}</a></li>
                {% empty %}
                    <span>暂无推荐 !</span>
                {% endfor %}
            </ul>
        </div>
        <div class="news" id="latest">
            <h2 class="newstitle"><span><a href="{% url 'blog:blog' %}"><u>更多</u></a></span><b>最新推荐</b></h2>
            <ul>
                {% for post in new_recommend %}
                    <li><a class="hvr-curl-bottom-right" href="{% url 'blog:detail' post.id %}" target="_Blank"><span>{{ post.created_time|date:"Y-m-d" }}</span>{{ post.title|striptags|truncatechars:23|safe }}</a></li>
                {% empty %}
                    <span>暂无推荐 !</span>
                {% endfor %}
            </ul>
      </div>
    </div>
    {% endblock side_list %}

{% endblock content %}

{% block script_extends %}
    <script type="text/javascript" rel="stylesheet" src="{% static 'blog/blog.js' %}"></script>
{% endblock %}

blog/templates/blog/category.html
{% extends 'blog/blog.html' %}
{% load post_tags %}
{% load staticfiles %}

{# 页面标题 #}
{% block title %}
    蒋振飞个人博客 - 分类 - {{ category_name }}
{% endblock title %}
{% block nav_blog_active %}{% endblock %}
{% block nav_category_active %}active{% endblock %}

{% block nav_route %}
    <div class="welcome">您现在的位置是：<a href="{% url 'blog:home' %}">首页</a> > <a href="{% url 'blog:category' 1 %}">全部分类</a></div>
{% endblock nav_route %}

{% block side_list %}
    <div class="rside">
        <div class="news">
            <h2 class="newstitle"><span><a href="{% url 'blog:blog' %}"><u>更多</u></a></span><b>博客分类</b></h2>
            <ul>
                {% for category in category_list %}
                <li>
                    <a class="hvr-buzz-out" href="{% url 'blog:category' category.id %}">{{ category }}&nbsp;({% get_category_count category %})</a>
                </li>
            {% empty %}
                <span>暂无分类 !</span>
            {% endfor %}
            </ul>
        </div>
        <div class="news">
            <h2 class="newstitle"><span><a href="{% url 'blog:blog' %}"><u>更多</u></a></span><b>日期归档</b></h2>
            <ul>
                {% for post_date in date_list %}
                    <li>
                        <a class="hvr-buzz-out" href="{% url 'blog:date' post_date.year post_date.month %}">
                            {% get_date_to_month post_date %}&nbsp;({% get_date_count post_date.year post_date.month %})
                        </a>
                    </li>
                {% empty %}
                    <span>暂无归档 !</span>
                {% endfor %}
            </ul>
        </div>
    </div>
{% endblock side_list %}

blog/templates/blog/date.html
{% extends 'blog/category.html' %}
{% load post_tags %}
{% load staticfiles %}
{#页面标题#}
{% block title %}
    蒋振飞个人博客 - 归档 - {{ post_time }}
{% endblock title %}

{% block nav_blog_active %}{% endblock %}
{% block nav_category_active %}{% endblock %}
{% block nav_date_active %}active{% endblock %}

{% block nav_route %}
    <div class="welcome">您现在的位置是：<a href="{% url 'blog:home' %}">首页</a> > <a href="{% url 'blog:date' 2018 12 %}">日期归档</a></div>
{% endblock nav_route %}

blog/templates/blog/other.html
{% extends 'blog/blog.html' %}
{% load post_tags %}
{% load staticfiles %}

{# 页面标题 #}
{% block title %}
    蒋振飞个人博客 - 其他文章

{% endblock title %}
{% block nav_blog_active %}{% endblock %}
{% block nav_category_active %}active{% endblock %}

{% block nav_route %}
    <div class="welcome">您现在的位置是：<a href="{% url 'blog:home' %}">首页</a> >
        <a href="{% url 'blog:other' %}">其他文章</a>
        {% if category_name %}
         > <span>{{category_name}}</span>
        {% endif %}
    </div>
{% endblock nav_route %}

blog/templates/blog/record.html
{% extends 'user/about.html' %}
{% load static from staticfiles %}

{#页面标题#}
{% block title %}蒋振飞个人博客 - 文章归档{% endblock title %}

{#目录触发#}
{% block nav_about_active %}active{% endblock %}
{% block nav_blog_active %}{% endblock %}

{% block header_extend %}
    <link rel="stylesheet" href="{% static 'about/about.css' %}">
    <script src="{% static 'about/about.js' %}"></script>
{% endblock %}

{% block nav_route %}
    <div class="welcome">您现在的位置是：<a href="{% url 'blog:home' %}">首页</a> > <a href="{% url 'blog:record' %}">文章归档</a></div>
{% endblock nav_route %}

{% block contentbox %}
    <ul>
        {% for post in post_list %}
            <li><a class="hvr-curl-bottom-right" href="{% url 'blog:detail' post.id %}" target="_Blank"><span>{{ post.created_time|date:"Y-m-d" }}</span>：{{ post.title}}</a></li>
        {% empty %}
            <span>暂无排行 !</span>
        {% endfor %}
    </ul>
{% endblock contentbox %}