blog/urls.py
# _*_ coding:utf-8 _*_

from django.conf.urls import url
from . import views

urlpatterns = [
    url(r'^$', views.home, name='home'),  # 访问地址:主机名+端口号/
    url(r'^detail/(?P<pk>\d+)$', views.detail, name='detail'),  # 访问地址:主机名+端口号/detail/pk
    url(r'^category/(?P<pk>\d+)$', views.category, name='category'),  # 访问地址:主机名+端口号/category/pk
    url(r'^blog', views.blog, name='blog'),  # 访问地址:主机名+端口号/blog
    url(r'^ajax_blog', views.ajax_blog, name='ajax_blog'),  # 访问地址:主机名+端口号/blog
    url(r'^date/(\d+)/(\d+)', views.date, name='date'),  # 访问地址:主机名+端口号/date/年/月
    url(r'^findWords', views.findWords, name='findWords'),
    url(r'^looking', views.looking, name='looking'),
    url(r'^record/$', views.record, name='record'),
    url(r'^read_charts/$', views.read_charts, name='read_charts'),
    url(r'^other/$', views.other, name='other'),
]

handler404 = views.page_not_found

blogproject/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from blog.search_indexes import MySeachView
import xadmin


urlpatterns = [
    url(r'^task/', admin.site.urls),
    url(r'^xadmin/', xadmin.site.urls),
    # 通过在根目录下的url加上namespace属性可以实现反向解析的功能
    # 注意:在根目录的url为namespace而项目的url是name
    url(r'^', include('blog.urls', namespace='blog')),    # 该地址就在ip根目录下
    url(r'^', include('comment.urls', namespace='comment')),
    url(r'^', include('likes.urls', namespace='likes')),
    url(r'^', include('user.urls', namespace='user')),
    url(r'^search/', MySeachView(), name='haystack_search'),
    url(r'^ueditor/', include('DjangoUeditor.urls')),
    url(r'^oauth/', include('oauth.urls', namespace='oauth')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

oauth/urls.py
from django.conf.urls import include, url
from oauth import views as oauth_views

urlpatterns = [
    # 其他的就省略不显示

    url(r'github_login', oauth_views.github_login, name='github_login'),
    url(r'github_check', oauth_views.github_check, name='github_check'),
    url(r'qq_login', oauth_views.qq_login, name='qq_login'),
    url(r'qq_check', oauth_views.qq_check, name='qq_check'),
    url(r'weibo_login', oauth_views.weibo_login, name='weibo_login'),
    url(r'weibo_check', oauth_views.weibo_check, name='weibo_check'),
    url(r'email', oauth_views.bind_email, name='bind_email'),   # 通过邮箱将第三方账户绑定到本站账号

]

user/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
    url(r'^user/register_for_modal/', views.register_for_modal, name='register_for_modal'),  # 访问地址:主机名+端口号/register
    url(r'^login_for_modal/', views.login_for_modal, name='login_for_modal'),
    url(r'^user/logout/', views.logout, name='logout'),
    url(r'^user/profile/', views.profile, name='profile'),
    url(r'^about/', views.about, name='about'),
    url(r'^user/chname/', views.chname, name='chname'),
    url(r'^user/chpwd/', views.chpwd, name='chpwd'),
    url(r'^user/forgotpwd/', views.forgot_password_modal, name='forgot_password_modal'),
    url(r'^user/email/', views.bind_email, name='bind_email'),
    url(r'^send_verification_code/', views.send_verification_code, name='send_verification_code'),
]

user/models.py
from django.db import models
from django.contrib.auth.models import User


class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE, verbose_name='用户名')
    nickname = models.CharField(max_length=20, verbose_name='昵称')
    image_url = models.URLField(default='', verbose_name='头像地址')

    def __str__(self):
        return self.nickname

    class Meta:
        verbose_name = '昵称'
        verbose_name_plural = '昵称'


def get_nickname(self):
    if Profile.objects.filter(user=self).exists():
        profile = Profile.objects.get(user=self)
        return profile.nickname
    else:
        return ''


def get_nickname_or_username(self):
    if Profile.objects.filter(user=self).exists():
        profile = Profile.objects.get(user=self)
        if profile.nickname:
            return profile.nickname
        return self.username
    else:
        return self.username


def has_nickname(self):
    return Profile.objects.filter(user=self).exists()


def get_image_url(self):
    if Profile.objects.filter(user=self).exists():
        profile = Profile.objects.get(user=self)
        return profile.image_url
    else:
        return ''


User.get_nickname = get_nickname
User.get_nickname_or_username = get_nickname_or_username
User.has_nickname = has_nickname
User.get_image_url = get_image_url

user/forms.py
from django import forms  # django表单功能
from django.contrib import auth
from django.contrib.auth.models import User


class LoginModalForm(forms.Form):
    """
    用户登录表单
    """
    # 用户名
    username_or_email = forms.CharField(label='帐号',
                                        widget=forms.TextInput(
                                            attrs={'class': 'form-control', 'placeholder': '请输入用户名或邮箱'}))

    # 密码
    password = forms.CharField(label='密码',
                               widget=forms.PasswordInput(
                                   attrs={'class': 'form-control', 'placeholder': '请输入密码'}))

    def clean(self):
        """
        清洗输入不合格的表单
        :return: 清洗后的数据
        """
        username_or_email = self.cleaned_data['username_or_email']
        password = self.cleaned_data['password']
        user = auth.authenticate(username=username_or_email, password=password)
        # 判断用户是否存在
        if user is None:
            if User.objects.filter(email=username_or_email).exists():
                username = User.objects.get(email=username_or_email).username
                user = auth.authenticate(username=username, password=password)
                if not user is None:
                    self.cleaned_data['user'] = user
                    return self.cleaned_data
                else:
                    raise forms.ValidationError('用户名或密码不正确,请重试')

            raise forms.ValidationError('用户名或密码不正确,请重试')
        else:
            self.cleaned_data['user'] = user
        return self.cleaned_data


class RegModalForm(forms.Form):
    """
    用户注册表单
    """
    # 用户名
    username = forms.CharField(
        label='账号',
        max_length=20,
        min_length=3,
        widget=forms.TextInput(
           attrs={'class': 'form-control', 'placeholder': '请输入用户名'}))

    # 邮箱
    email = forms.EmailField(
        label='邮箱',
        widget=forms.EmailInput(
            attrs={'class': 'form-control', 'placeholder': '请输入邮箱'}))

    # 密码
    password = forms.CharField(
        label='密码',
        min_length=6,
        widget=forms.PasswordInput(
           attrs={'class': 'form-control', 'placeholder': '请输入密码'}))

    # 再次输入密码
    # password_again = forms.CharField(
    #     label='密码',
    #     min_length=6,
    #     widget=forms.PasswordInput(
    #         attrs={'placeholder': '再输入一次密码'}))

    # 验证码
    verification_code = forms.CharField(
        label='验证码',
        required=False,
        widget=forms.TextInput(
            attrs={'class': 'form-control', 'placeholder': '请在邮箱中查收'}
        )
    )

    def __init__(self, *args,  **kwargs):
        if 'request' in kwargs:
            self.request = kwargs.pop('request')
        super(RegModalForm, self).__init__(*args, **kwargs)

    # def clean_username(self):
    #     """
    #     清洗输入的用户名
    #     :return: 清洗后的用户名
    #     """
    #     username = self.cleaned_data['username']
    #     if User.objects.filter(username=username).exists():
    #         raise forms.ValidationError('用户名已存在')
    #     return username

    # def clean_email(self):
    #     """
    #     清洗输入的邮箱
    #     :return: 清洗后的邮箱
    #     """
    #     email = self.cleaned_data['email']
    #     if User.objects.filter(email=email).exists():
    #         raise forms.ValidationError('邮箱已存在')
    #     return email

    # def clean_verification_code(self):
    #     code = self.request.session.get('register_code', '').lower()
    #     verification_code = self.cleaned_data.get('verification_code', '').lower()
    #     if not (code != '' and code == verification_code):
    #         raise forms.ValidationError('验证码不正确')
    #     return self.cleaned_data

    # def clean_password_again(self):
    #     """
    #     清洗第二次输入的密码
    #     :return: 输入一致的密码
    #     """
    #     password = self.cleaned_data['password']
    #     password_again = self.cleaned_data['password_again']
    #
    #     if password != password_again:
    #         raise forms.ValidationError('两次输入的密码不一致')
    #     return password


class ChangeNameForm(forms.Form):
    new_nickname = forms.CharField(
        label='新昵称',
        max_length=20,
        min_length=3,
        widget=forms.TextInput(
            attrs={'placeholder': '请输入新的昵称'}
        )
    )

    def __init__(self, *args,  **kwargs):
        if 'user' in kwargs:
            self.user = kwargs.pop('user')
        super(ChangeNameForm, self).__init__(*args, **kwargs)

    def clean(self):
        # 验证用户是否处在登录状态
        if self.user.is_authenticated:
            self.cleaned_data['user'] = self.user
        else:
            raise forms.ValidationError('用户尚未登录')
        return self.cleaned_data

    def clean_new_nickname(self):
        new_nickname = self.cleaned_data.get('new_nickname', '').strip()
        if new_nickname == '':
            raise forms.ValidationError("新的昵称不能为空")
        return new_nickname


class ChangePasswordForm(forms.Form):

    past_password = forms.CharField(
        label='原密码',
        min_length=6,
        widget=forms.PasswordInput(
            attrs={'placeholder': '请输入原密码'}
        )
    )

    new_password = forms.CharField(
        label='新密码',
        min_length=6,
        widget=forms.PasswordInput(
            attrs={'placeholder': '请输入新密码'}
        )
    )

    # new_password_again = forms.CharField(
    #     label='新密码',
    #     min_length=6,
    #     widget=forms.PasswordInput(
    #         attrs={'placeholder': '再输入一次密码'}
    #     )
    # )

    def __init__(self, *args,  **kwargs):
        if 'user' in kwargs:
            self.user = kwargs.pop('user')
        super(ChangePasswordForm, self).__init__(*args, **kwargs)

    # def clean(self):
    #     # 验证新密码是否一致
    #     new_password = self.cleaned_data.get('new_password', '')
    #     new_password_again = self.cleaned_data.get('new_password_again', '')
    #     if new_password != new_password_again or new_password == '':
    #         raise forms.ValidationError('两次输入密码不一致')
    #     return self.cleaned_data

    def clean_past_password(self):
        """验证原密码是否正确"""
        past_password = self.cleaned_data.get('past_password', '')
        if not self.user.check_password(past_password):
            raise forms.ValidationError('原密码不正确')
        return past_password


class BindEmailForm(forms.Form):
    email = forms.EmailField(
        label='邮箱',
        widget=forms.EmailInput(
            attrs={'placeholder': '请输入邮箱'}
        )
    )
    verification_code = forms.CharField(
        label='验证码',
        required=False,
        widget=forms.TextInput(
            attrs={'placeholder': '请在邮箱中查收'}
        )
    )

    def __init__(self, *args,  **kwargs):
        if 'request' in kwargs:
            self.request = kwargs.pop('request')
        super(BindEmailForm, self).__init__(*args, **kwargs)

    def clean(self):
        # 验证用户是否处在登录状态
        if self.request.user.is_authenticated:
            self.cleaned_data['user'] = self.request.user
        else:
            raise forms.ValidationError('用户尚未登录')

        # 判断用户是否已绑定邮箱
        if self.request.user.email != '':
            raise forms.ValidationError('你已经绑定邮箱')

        # 判断验证码
        # code = self.request.session.get('bind_email_code', '')
        # verification_code = self.cleaned_data.get('verification_code', '')
        # if not (code != '' and code == verification_code):
        #     raise forms.ValidationError('验证码不正确')

        return self.cleaned_data

    def clean_email(self):
        email = self.cleaned_data['email']
        if User.objects.filter(email=email).exists():
            raise forms.ValidationError('该邮箱已被绑定')
        return email

    def clean_verification_code(self):
        code = self.request.session.get('bind_eamil_code', '').lower()
        verification_code = self.cleaned_data.get('verification_code', '').lower()
        if not (code != '' and code == verification_code):
            raise forms.ValidationError('验证码不正确')
        return self.cleaned_data


class ForgotPasswordModalForm(forms.Form):
    # 邮箱
    password_email = forms.EmailField(
        label='邮箱',
        widget=forms.EmailInput(
            attrs={'class': 'form-control', 'placeholder': '请输入绑定过的邮箱'}
        )
    )

    new_password = forms.CharField(
        label='密码',
        min_length=6,
        widget=forms.PasswordInput(
            attrs={'class': 'form-control', 'placeholder': '请输入新密码'}
        )
    )

    # 验证码
    password_verification_code = forms.CharField(
        label='验证码',
        required=False,
        widget=forms.TextInput(
            attrs={'class': 'form-control', 'placeholder': '请在邮箱中查收'}
        )
    )

    def __init__(self, *args,  **kwargs):
        if 'request' in kwargs:
            self.request = kwargs.pop('request')
        super(ForgotPasswordModalForm, self).__init__(*args, **kwargs)

    # def clean_email(self):
    #     email = self.cleaned_data['email'].strip()
    #
    #     if not User.objects.filter(email=email).exists():
    #         raise forms.ValidationError('邮箱不存在')
    #     return email
    #
    # def clean_password_verification_code(self):
    #     verification_code = self.cleaned_data.get('password_verification_code', '').strip()
    #     if verification_code == '':
    #         raise forms.ValidationError('验证码不能为空')
    #
    #     # 判断验证码
    #     code = self.request.session.get('forgot_password_code', '').lower()
    #     verification_code = self.cleaned_data.get('verification_code', '').lower()
    #     if not (code != '' and code == verification_code):
    #         raise forms.ValidationError('验证码不正确')
    #
    #     return verification_code


    def clean_new_password(self):
        new_password = self.cleaned_data.get('new_password', '')
        if new_password == '':
            raise forms.ValidationError('密码不能为空')
        return new_password

user/templates/user/bind_email.html
{% extends 'base.html' %}
{% load staticfiles %}

{% block title %}
    绑定邮箱
{% endblock %}

{% block nav_login_active %}active{% endblock %}
{% block lunbobox %}{% endblock %}

{% block content %}
    <div class="container" style="margin-top: 60px;">
        {% if user.is_authenticated %}
            <div class="head-login">
                <h2 class="text-info">绑定邮箱</h2>
                <span>和你在一起压力好大，是谁让你这么优秀</span>
            </div>

            <div class="bind_email">
                <form action="" method="POST" class="clearfix">
                     {% csrf_token %}
                    <input name="referer" type="hidden" value="{{ referer }}">
                     {% for field in email_form %}
                         <label for="{{ field.id_for_label }}">{{ field.label }}:</label>
                         {{ field }}
                         <p class="text-danger">{{ field.errors.as_text }}</p>
                     {% endfor %}
                    {# 错误信息标红 #}
                    <span id="tip" class="text-danger">{{ login_form.non_field_errors }}</span>
                    <div class="clearfix"></div>
                    <input class="btn btn-primary pull-right" type="submit" value="绑定">
                    <button id="send_code" class="btn btn-primary pull-left">发送验证码</button>
                    <div class="clearfix"></div>
                </form>
{#                <button style="margin-top: 27px" class="btn btn-default pull-right" onclick="window.location.href={{ return_back_url }}">返回</button>#}
            </div>
        {% else %}
            <div style="width: 500px;margin:auto;margin-top: 150px;">
                <h4 class="text-center">
                    <span>您尚未登录，<span id="time_left">3</span>秒后跳转到首页...</span>
                </h4>
            </div>
            <script type="text/javascript">
                $(function(){
                    var time = 3000 / 1000;
                    intervalid = window.setInterval(function(){
                        if (time <= 0){
                            clearInterval(intervalid);
                            window.location = '/';
                        }
                        $('#time_left').text(time);
                        time -= 1;
                    },1000);
                });
            </script>
        {% endif %}

    </div>
{% endblock %}

{% block script_extends %}
    <script type="text/javascript">
        $("#send_code").click(function () {
           var email = $("#id_email").val()
            //判断邮箱是否为空
            if(email==""){
               $("#tip").text('邮箱不能为空');
               return false;
            }
            //发送验证码
            $.ajax({
                url: '{% url 'user:send_verification_code' %}',
                type: 'GET',
                data: {
                    'email': email,
                    'send_for': 'bind_eamil_code'
                },
                cache: false,
                success: function (data) {
                    if(data['status']=='ERROR'){
                        alert('当前请求过于频繁！');

                    }
                }
            });
           //把按钮变灰
            $(this).addClass('disabled');
            $(this).attr('disabled', true);
            var time = 30;
            $(this).text(time + 's');
            var interval = setInterval(() => {
                if(time <= 0){
                    clearInterval(interval);
                    $(this).removeClass('disabled');
                    $(this).attr('disabled', false);
                    $(this).text('发送验证码');
                    return false;
                }

                time --;
                $(this).text(time + 's');
            }, 1000);
        });
    </script>
{% endblock %}

user/templates/user/chname.html
{% extends 'user/about.html' %}

{% block title %}蒋振飞个人博客 - {{ user.username }}{% endblock %}

{% block nav_route %}
    <div class="welcome">您现在的位置是：<a href="{% url 'blog:home' %}">首页</a> > <a href="{% url 'user:profile' %}">用户中心</a>><a href="{% url 'user:chname' %}">修改昵称</a></div>
{% endblock nav_route %}

{% block contentbox %}
    {% if user.is_authenticated %}

        <div class="head-login" style="text-align: center">
            <h2 class="text-info">修改昵称</h2>
            <span>机智如你，看看谁的昵称最好听</span>
        </div>

        <div class="input-submit clearfix">
             <form action="" method="POST">
             {% csrf_token %}
                 <input name="referer" type="hidden" value="{{ referer }}">
             {% for field in name_form %}
                 <label for="{{ field.id_for_label }}">{{ field.label }}:</label>
                 {{ field }}
                 <div class="text-danger">{{ field.errors.as_text }}</div>
             {% endfor %}
                {# 错误信息标红 #}
                 <span class="text-danger">{{ login_form.non_field_errors }}</span>
                 <button class="btn btn-primary pull-right" type="submit">修改</button>
            </form>

        </div>
    {% else %}

        <h4 class="text-center">
            <span>您尚未登录，<span id="time_left">3</span>秒后跳转到首页...</span>
        </h4>

         <script type="text/javascript">
            $(function(){
                var time = 3000 / 1000;
                intervalid = window.setInterval(function(){
                    if (time <= 0){
                        clearInterval(intervalid);
                        window.location = '/';
                    }
                    $('#time_left').text(time);
                    time -= 1;
                },1000);
            });
        </script>
    {% endif %}
{% endblock contentbox %}

user/templates/user/chpwd.html
{% extends 'user/about.html' %}

{% block title %}蒋振飞个人博客 - {{ user.username }}{% endblock %}

{% block nav_route %}
    <div class="welcome">您现在的位置是：<a href="{% url 'blog:home' %}">首页</a>><a href="{% url 'user:profile' %}">用户中心</a> > <a href="{% url 'user:chpwd' %}">修改密码</a></div>
{% endblock nav_route %}

{% block contentbox %}
    {% if user.is_authenticated %}

        <div class="head-login" style="text-align: center">
            <h2 class="text-info">修改密码</h2>
            <span>您的密码会被加密保存，请放心使用</span>
        </div>

        <div class="input-submit clearfix">
             <form action="" method="POST">
             {% csrf_token %}
                 <input name="referer" type="hidden" value="{{ referer }}">
             {% for field in password_form %}
                 <label for="{{ field.id_for_label }}">{{ field.label }}:</label>
                 {{ field }}
                 <div class="text-danger">{{ field.errors.as_text }}</div>
             {% endfor %}
                {# 错误信息标红 #}
                 <span class="text-danger">{{ login_form.non_field_errors }}</span>
                 <button class="btn btn-primary pull-right" type="submit">修改</button>
            </form>

        </div>
    {% else %}
        <h4 class="text-center">
            <span>您尚未登录，<span id="time_left">3</span>秒后跳转到首页...</span>
        </h4>
         <script type="text/javascript">
            $(function(){
                var time = 3000 / 1000;
                intervalid = window.setInterval(function(){
                    if (time <= 0){
                        clearInterval(intervalid);
                        window.location = '/';
                    }
                    $('#time_left').text(time);
                    time -= 1;
                },1000);
            });
        </script>
    {% endif %}
{% endblock contentbox %}

user/templates/user/profile.html
{% extends 'user/about.html' %}

{% block title %}蒋振飞个人博客 - {{ user.username }}{% endblock %}

{% block nav_route %}
    <div class="welcome">您现在的位置是：<a href="{% url 'blog:home' %}">首页</a> > <a href="{% url 'user:profile' %}">用户中心</a></div>
{% endblock nav_route %}

{% block contentbox %}

    {% if user.is_authenticated %}

        <div>
            <h3 style="color: #09b1b9">我的信息</h3>
            <div class="user-info">
                <h3 style="margin: 10px">{{ user.username }}</h3>
                <p>
                    昵称：{{ user.get_nickname }}
                    {% if user.get_nickname %}
                    <u><a style="margin-left: 0.5em" href="{% url 'user:chname' %}">修改昵称</a></u>
                    {% else %}
                        <u><a href="{% url 'user:chname' %}">添加昵称</a></u>
                    {% endif %}
                </p>
                <p>注册邮箱：
                    {% if user.email %}
                        {{ user.email }} (已绑定)
                    {% else %}
                        未绑定 <u><a href="{% url 'user:bind_email' %}">绑定邮箱</a></u>
                    {% endif %}
                </p>
                <p>加入时间：{{ user.date_joined }}</p>
                <p>上次登录时间：{{ user.last_login}}</p>
                <p>当前访问IP地址：{{ address_ip }}</p>
                <p><u><a href="{% url 'user:chpwd' %}">修改密码</a></u></p>
            </div>
        </div>

    {% else %}
        <h2 class="text-center">未登录</h2>
         <p class="text-center">
            <span>未登录，<span id="time_left">3</span>秒后跳转到首页...</span>
        </p>
        <script type="text/javascript">
            $(function(){
                var time = 3000 / 1000;
                intervalid = window.setInterval(function(){
                    if (time <= 0){
                        clearInterval(intervalid);
                        window.location = '/';
                    }
                    $('#time_left').text(time);
                    time -= 1;
                },1000);
            });
        </script>
    {% endif %}

{% endblock contentbox %}

user/templates/user/register.html
{% extends 'base.html' %}
{% load staticfiles %}

{% block title %}
     注册 - 蒋振飞的博客
{% endblock %}

{% block nav_register_active %}active{% endblock %}
{% block lunbobox %}{% endblock %}

{% block content %}
    <div class="container" style="margin-top: 60px;">
        {% if user.is_authenticated %}
            <div style="width: 500px;margin:auto;margin-top: 150px;">
                <h2 class="text-center">已登录</h2>
                <p class="text-center">
                    <span>您已登录，<span id="time_left">3</span>秒后跳转到首页...</span>
                </p>
            </div>
              <script type="text/javascript">
                $(function(){
                    var time = 3000 / 1000;
                    intervalid = window.setInterval(function(){
                        if (time <= 0){
                            clearInterval(intervalid);
                            window.location = '/';
                        }
                        $('#time_left').text(time);
                        time -= 1;
                    },1000);
                });
            </script>
        {% else %}

            <div class="head-register clearfix">
                <h2 class="text-info">欢迎注册用户</h2>
                <span>小心保管自己的密码，千万不要告诉别人哟！</span>
            </div>

            <div class="register">
                <form action="" method="POST">
                {% csrf_token %}
                    <input name="referer" type="hidden" value="{{ referer }}">
                {% for field in reg_form %}
                    {# label去冒号 #}
                    <label for="{{ field.id_for_label }}">{{ field.label }}:</label>
                        {{ field }}
                    <p class="text-danger">{{ field.errors.as_text }}</p>
                {% endfor %}
                    <span class="other_account">第三方账号登录：
                         <a href="{% url 'oauth:github_login' %}" title="Github登录">
                             <img src="{% static 'blog/media/github.ico' %}" alt="Github登录">
                         </a>
                            {# <a href="/oauth/oauth_login/QQ?state=https://jzfblog.com/" title="QQ登录">#}
                            <img src="{% static 'blog/media/qq.ico' %}" alt="QQ登录">
                            {# </a>#}
                        {# <a href="{% url 'oauth:github_login' %}" title="Github登录">#}
                             &nbsp;<img src="{% static 'blog/media/weibo.ico' %}" alt="微博登录">
                        {# </a>#}
                    </span>
                    {# 错误信息标红 #}
                      <span class="pull-left text-danger">{{ login_form.non_field_errors }}</span>
                    {# <span>用户名：</span> #}
                    {# <input type="text" name="username"> #}
                    {# <span>密码：</span> #}
                    {# <input type="password" name="password"> #}
                    {# <span style="font-weight: bold;">已有帐号？<a style="color: #337ab7;" href="{% url 'user:login' %}">点击登录</a></span>#}
                    <div class="clearfix" style="height: 5px"></div>
                    <button class="btn btn-primary pull-right" type="submit">注册</button>
                    <button id="send_code" class="btn btn-primary pull-left">发送验证码</button>
                </form>

                <div class="register-button hidden-xs">
                    <p class="no-user"> 已有账号？</p>
                    <p>
                        <a href="{% url 'user:login' %}">
                        <button class="btn btn-default" type="submit">点击登录</button>
                        </a>
                    </p>
                    <p class="no-user"> 忘记密码？</p>
                    <p>
                        <a href="{% url 'user:forgot_password' %}">
                        <button class="btn btn-default" type="submit">点击找回</button>
                        </a>
                    </p>
                </div>
            </div>

        {% endif %}
    </div>
{% endblock %}

{% block script_extends %}
    <script type="text/javascript">
        $("#send_code").click(function () {
           var email = $("#id_email").val()
            //判断邮箱是否为空
            if(email==""){
               $("#tip").text('邮箱不能为空');
               return false;
            }
            //发送验证码
            $.ajax({
                url: '{% url 'user:send_verification_code' %}',
                type: 'GET',
                data: {
                    'email': email,
                    'send_for': 'register_code'
                },
                cache: false,
                success: function (data) {
                    if(data['status']=='ERROR'){
                        alert('当前请求过于频繁！');
                    }
                }
            });
           //把按钮变灰
            $(this).addClass('disabled');
            $(this).attr('disabled', true);
            var time = 30;
            $(this).text(time + 's');
            var interval = setInterval(() => {
                if(time <= 0){
                    clearInterval(interval);
                    $(this).removeClass('disabled');
                    $(this).attr('disabled', false);
                    $(this).text('发送验证码');
                    return false;
                }

                time --;
                $(this).text(time + 's');
            }, 1000);
        });
    </script>
{% endblock %}